import { getRecentDate } from './helpers';
import { getTranslation } from './translations';

export const generateMockBlogs = (lang = 'en') => {
  const t = (key) => getTranslation(lang, key);

  return [
    {
      id: 1,
      title: t('mockBlog1Title'),
      description: t('mockBlog1Desc'),
      category: 'Lifestyle',
      author: t('mockBlog1Author'),
      status: 'Publish',
      publishDate: getRecentDate(2),
      views: 12500,
      image: 'https://images.unsplash.com/photo-1533052697893-9c86d8a7c293?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 2,
      title: t('mockBlog2Title'),
      description: t('mockBlog2Desc'),
      category: 'Health',
      author: t('mockBlog2Author'),
      status: 'Publish',
      publishDate: getRecentDate(5),
      views: 9800,
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 3,
      title: t('mockBlog3Title'),
      description: t('mockBlog3Desc'),
      category: 'Technology',
      author: t('mockBlog3Author'),
      status: 'Publish',
      publishDate: getRecentDate(1),
      views: 18200,
      image: 'https://images.unsplash.com/photo-1593642632823-8f78536788c6?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 4,
      title: t('mockBlog4Title'),
      description: t('mockBlog4Desc'),
      category: 'Lifestyle',
      author: t('mockBlog4Author'),
      status: 'Publish',
      publishDate: getRecentDate(8),
      views: 7400,
      image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 5,
      title: t('mockBlog5Title'),
      description: t('mockBlog5Desc'),
      category: 'Lifestyle',
      author: t('mockBlog5Author'),
      status: 'Publish',
      publishDate: getRecentDate(3),
      views: 15600,
      image: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 6,
      title: t('mockBlog6Title'),
      description: t('mockBlog6Desc'),
      category: 'Technology',
      author: t('mockBlog6Author'),
      status: 'Publish',
      publishDate: getRecentDate(12),
      views: 22100,
      image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 7,
      title: t('mockBlog7Title'),
      description: t('mockBlog7Desc'),
      category: 'Lifestyle',
      author: t('mockBlog7Author'),
      status: 'Publish',
      publishDate: getRecentDate(15),
      views: 11300,
      image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 8,
      title: t('mockBlog8Title'),
      description: t('mockBlog8Desc'),
      category: 'Health',
      author: t('mockBlog8Author'),
      status: 'Publish',
      publishDate: getRecentDate(20),
      views: 19500,
      image: 'https://images.unsplash.com/photo-1511295742362-92c96b5aabb5?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 9,
      title: t('mockBlog9Title'),
      description: t('mockBlog9Desc'),
      category: 'Finance',
      author: t('mockBlog9Author'),
      status: 'Publish',
      publishDate: getRecentDate(6),
      views: 25900,
      image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 10,
      title: t('mockBlog10Title'),
      description: t('mockBlog10Desc'),
      category: 'Education',
      author: t('mockBlog10Author'),
      status: 'Draft',
      publishDate: getRecentDate(0),
      views: 0,
      image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=800',
    },
  ];
};
